- .github/workflows/pipeline.yml
- Published release is created, no draft anymore.
- Version included in the tag.
- Changelog included in release message. Right now complete changelog is included, would be nice to have only the delta.
- No `changeset publish` step required (this is used for publishing to npmjs).
> fix: tag and descr in pipeline workflow

- .changeset/serious-buses-punch.md
- packages/webapp/src/webview/ui/components/App/App.scss
- packages/webapp/src/webview/ui/components/Header/Header.scss
Related Issue: BUG- Search box overlaps Guided Answers title on reducing width
#109 
Description: Added media queries to make the search bar drop-down at smaller viewports
> Bug fix: Search box overlaps Guided Answers title on reducing width

- packages/ide-extension/test/__mocks__/vscode.js
- packages/ide-extension/test/enhancement/commandHandler.test.ts
- packages/types/src/typeGuards.ts
- packages/types/src/types.ts
Missing unit test for module `sap-guided-answers-extension`
- test added for handleCommand()
> test: unit test for sap-guided-answers-extension

- .changeset/dull-carpets-build.md
- docs/technical-information.md
- packages/core/src/guided-answers-api.ts
- packages/core/test/__snapshots__/guided-answers-api.test.ts.snap
- packages/core/test/guided-answers-api.test.ts
- packages/ide-extension/esbuild.js
- packages/ide-extension/package.json
- packages/ide-extension/src/extension.ts
- packages/ide-extension/src/panel/guidedAnswersPanel.ts
- packages/ide-extension/src/types.ts
- packages/ide-extension/test/__mocks__/vscode.js
- packages/ide-extension/test/extension.test.ts
- packages/ide-extension/test/panel/guidedAnswersPanel.test.ts
- packages/types/src/actions.ts
- packages/types/src/types.ts
- packages/webapp/package.json
- packages/webapp/src/webview/state/reducers.ts
- packages/webapp/src/webview/types.ts
- packages/webapp/src/webview/ui/components/App/App.scss
- packages/webapp/src/webview/ui/components/App/App.tsx
- packages/webapp/src/webview/ui/components/Header/SearchField/SearchField.tsx
- packages/webapp/test/App.test.tsx
- pnpm-lock.yaml
https://github.com/SAP/guided-answers-extension/issues/174
Add functionality to call Guided Answers command with node path parameter, e.g.:
```
commands.executeCommand('sap.ux.guidedAnswer.openGuidedAnswer', { treeId: 3046, nodeIdPath: [45995, 45996, 46000] });
```
I've also adjusted `esbuild.js` and `package.json` of `ide-extension` to enable `watch` mode.
> feat: start ga command with node path

- .eslintrc
- package.json
- packages/core/package.json
- packages/core/src/environment.json
- packages/core/src/environment.ts
- packages/core/src/index.ts
- packages/core/test/environment.test.ts
- packages/core/tsconfig.json
- packages/ide-extension/package.json
- packages/ide-extension/src/enhancement/enhancements.ts
- packages/ide-extension/src/extension.ts
- packages/ide-extension/src/panel/guidedAnswersPanel.ts
- packages/ide-extension/src/types.ts
- packages/ide-extension/test/enhancement/commandHandler.test.ts
- packages/ide-extension/test/enhancement/enhancement.test.ts
- packages/ide-extension/test/extension.test.ts
- packages/ide-extension/test/panel/guidedAnswersPanel.test.ts
- pnpm-lock.yaml
https://github.com/SAP/guided-answers-extension/issues/245
Add initial filter for `SAP Fiori` SBAS devspace:
Due to dependency to `@sap/bas-sdk@2.1.2` this requires a new `override`, fix is on the way: https://github.wdf.sap.corp/devx-wing/bas-sdk/pull/101
> feat: set initial filter for environment

- packages/ide-extension/src/panel/guidedAnswersPanel.ts
- packages/webapp/src/webview/state/reducers.ts
- packages/webapp/src/webview/ui/components/App/App.tsx
memory leak due to `ResizeObserver.observe`
This PR is a proposal to move the `ResizeObserver` to react hook [onEffect()](https://reactjs.org/docs/hooks-effect.html).
Additionally it adds output log for search and sets the initial page size value to 20 for robustness reasons.
> fix: change resize handler to useEffect()

- .changeset/happy-points-check.md
- packages/webapp/src/webview/ui/components/Header/Filters/Filters.tsx
- packages/webapp/test/Header/Filters.test.tsx
https://github.com/SAP/guided-answers-extension/issues/300
When closing the filter dialog with "Cancel", the filer is still applied and results are added leading to multiple result nodes. This PR fixes this, "Cancel" closes the dialog and restores the previous filter values.
> fix(webapp): filter dialog cancel

- .changeset/sweet-pets-look.md
- packages/ide-extension/src/panel/guidedAnswersPanel.ts
#263
When another window is opened in the code editor VS code is opened to the side. If there are no windows opened, VS code is opened as full screen
> Feature- Open GA to side when called via other extensions

- .changeset/young-ravens-cough.md
- packages/webapp/esbuild.js
- packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackSentDialogBox/FeedbackSendDialogBox.tsx
https://github.com/SAP/guided-answers-extension/issues/385
Fix for re-opening 'Message sen' popup dialog.
> fix: re-opening message sent popup

- .changeset/config.json
- .changeset/long-chairs-teach.md
- packages/core/package.json
- packages/ide-extension/src/telemetry/action-map.ts
- packages/ide-extension/src/telemetry/telemetry.ts
- packages/ide-extension/test/telemetry/actions-map.test.ts
- packages/types/package.json
- packages/webapp/package.json
- pnpm-lock.yaml
https://github.com/SAP/guided-answers-extension/issues/122
- Fix for telemetry `SET_ACTIVE_TREE` with unit test
- Improved telemetry error logging
- enable patch for `@vscode/extension-telemetry@0.6.2`
- Use extension module name as prefix for telemetry events
- Consolidate internal module versioning
- Create fixed changeset packages
> fix: telemetry and private module consolidation

- .changeset/silent-spies-call.md
- .github/workflows/codeql-analysis.yml
- .github/workflows/pipeline.yml
- .github/workflows/reuse-compliance.yml
- package.json
- pnpm-lock.yaml
GitHub actions outdated
- upgrade to `actions/checkout@v3.3.0`
- remove node 14.x builds, set 16.x as default
- use `pnpm@7.28.0` as pnpm patches have not been applied with version `7.1.0`
- switch from `set-output` to `>> $GITHUB_OUTPUT` ([github-actions-deprecating-save-state-and-set-output-commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
- add current changes to release description only (leveraging `changelog-parser`)
Although not required, the branch of this PR has a changeset to test the full E2E cycle when merging this PR.
> chore: pipeline updates and improvements

- .changeset/ten-ghosts-reply.md
- packages/webapp/src/webview/ui/components/App/App.tsx
#434
Fixed bug where user was not able to navigate into the result list, when a filter is used
> fix(434): fix keyboard navigation for filters

- .changeset/afraid-tigers-cheat.md
- packages/ide-extension/src/panel/guidedAnswersPanel.ts
- packages/ide-extension/test/panel/guidedAnswersPanel.test.ts
- packages/webapp/src/webview/ui/components/Header/SearchField/SearchField.tsx
https://github.com/SAP/guided-answers-extension/issues/436
No interruption for input when starting search. However, if the search takes longer than 2000ms we still show a loading animation and the input is blocked.
> fix: no interruption for search input

- .changeset/tiny-walls-suffer.md
- packages/webapp/src/webview/ui/components/App/App.tsx
#442 
Fixed filters showing up in wrong app states like when a node path is open
> fix(442): fix filters showing app in wrong app states

- package.json
- packages/ide-extension/package.json
- pnpm-lock.yaml
xml2js is vulnerable to prototype pollution.
Fix
```
packages/ide-extension$ pnpm audit
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ xml2js is vulnerable to prototype pollution            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ xml2js                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <0.5.0                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=0.5.0                                                │
├─────────────────────┼───────────────────────────────────────── …
```
> fix: update xml2js due to vulnerability

- .changeset/loud-cameras-doubt.md
- packages/ide-extension/src/panel/guidedAnswersPanel.ts
- packages/ide-extension/test/panel/guidedAnswersPanel.test.ts
https://github.com/SAP/guided-answers-extension/issues/443
Change behavior after query was execute with URL: if the URL causes a successful navigation to a tree and node path, we clear the URL from the query field.
> fix: clear query when URL was detected

- .github/workflows/pipeline.yml
- package.json
- pnpm-lock.yaml
pnpm version outdated
There is a new version `pnpm@8.6.0` that we missed in our last update by a couple of days. This PR updates `pnpm `again.
> fix: use pnpm@8.6.0

- .changeset/polite-otters-camp.md
- packages/webapp/src/webview/ui/components/GuidedAnswerNavPath/GuidedAnswerNavPath.scss
#504
* Removed `box-sizing: border-box` that was set for all elements and created inconsistencies between this project and `open-ux-tools`
> fix(504): remove box sizing specifier for all elements

- packages/ide-extension/src/logger/logger.ts
- packages/ide-extension/src/telemetry/telemetry.ts
- packages/ide-extension/test/logger/logger.test.ts
- packages/ide-extension/test/telemetry/telemetry.test.ts
Too much noise in OUTPUT tab.
There are many messages in OUTPUT tab of Guided Answers extension. This PR introduces trace messages, that are for now added to console.log and can be seen in developer tools. 
Better way would be to use [Log output channel](https://code.visualstudio.com/updates/v1_73#_log-output-channel), but this would required to update the min supported VSCode version from `1.39.0` to `1.73` (October 2022).
Code is done in a way that makes it easy to switch to new `LogOutputChannel` afterwards.
> feat: improve logging and tracing

- packages/ide-extension/package.json
- pnpm-lock.yaml
Min supported Visual Studio Code version is old. 
Update min VSCode version to `1.73.1`.
Enables also the use of [Log output channel](https://code.visualstudio.com/updates/v1_73#_log-output-channel), see https://github.com/SAP/guided-answers-extension/pull/538
> chore: update min vscode version

- docs/testcases/View Guided Answers Content_V3.md
> Update View Guided Answers Content_V3.md

- pnpm-lock.yaml
#595 
Update transitive dependencies by running `pnpm update`
> chore: update transitive dependencies (#595)

- .github/workflows/pipeline.yml
Follow up to PR #594 where v2.1 was consumed but I wanted to consume v2.1.1
> chore: consume latest v2.1.1 of sonar cloud

- .changeset/rare-parents-press.md
- packages/webapp/src/webview/ui/components/App/App.scss
#338 
Set document overflow to auto when dialog is open
> fix: set document overflow style to prevent screen jump

- .changeset/fresh-frogs-appear.md
- pnpm-lock.yaml
#595 
Also solves security issue https://github.com/SAP/guided-answers-extension/security/dependabot/13
Update transitive dependencies by running `pnpm update`.
There was an issue as braces was not getting updated to `3.0.3` and hence deleting lock file and node_modules, running `pnpm install` did the trick.
> chore: update transitive dependencies and solve security issue (#595)

- package.json
- pnpm-lock.yaml
#595 
Changeset update is not required. No change to the source code.
In general as this is a extension and not consumed by other modules, we can release a new version combining multiple fixes.
- Remove unwanted override 
```
"overrides": {
"@babel/traverse@<7.23.2": ">=7.23.2"
}
```
- Update transitive dependencies by regeneration of lock file
> fix: remove unnecessary override and update transitive dependencies
