README.md

This PR adds link to SAP Note in ReadMe which discussed the Guided Answers API support guidelines.

 Added Guided Answers API support note

---

.github/PULL_REQUEST_TEMPLATE.md

Issue: https://github.com/SAP/guided-answers-extension/issues/116
This pr contains:
- Pull request template

feat: adding template for Pull Requests

---

.changeset/hot-cows-nail.md
packages/webapp/src/webview/ui/components/App/App.scss

https://github.com/SAP/guided-answers-extension/issues/123
Fix for missing numbers in lists.

fix: missing numbers in list

---

packages/core/src/guided-answers-api.ts
packages/ide-extension/src/enhancement/enhancements.ts
packages/ide-extension/src/panel/guidedAnswersPanel.ts
packages/webapp/src/webview/ui/components/GuidedAnswerNavPath/GuidedAnswerNavPath.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/GuidedAnswerNode.tsx

Sonar code smells
Fix several code smells found by SonarCloud

chore: sonar code smells

---

packages/testcases/View Guided Answers Content.md

#91
Test case for displaying Guided Answer content

View Guided Answers Content.md

---

.changeset/fifty-mails-heal.md
packages/ide-extension/src/enhancement/enhancements.json

https://github.com/SAP/guided-answers-extension/issues/144
Add ability to launch SAP Fiori tools Environment check command

add SAP Fiori tools Environment check

---

packages/webapp/test/Header/Logo.test.tsx
packages/webapp/test/Header/NavigationButtons.test.tsx

https://github.com/SAP/guided-answers-extension/issues/141
Tests for:
1. Logo
2. Navigation Buttons

feat(ga): backfill unit tests

---

packages/webapp/src/webview/ui/components/GuidedAnswerNode/GuidedAnswerNode.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Middle/Middle.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Middle/index.ts
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Right/Right.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Right/index.ts

#146 
Make smaller components in `GuidedAnswerNode` file for easier testing in #141

 Refactor GuidedAnswerNode file

---

packages/webapp/src/webview/ui/components/Header/Header.tsx

fix(ga): sonar code smell

---

.changeset/orange-monkeys-marry.md

chore: new version for cw27

---

packages/testcases/KeyboardNavigation

#134
Test case for 134
Subject to change after UX review

Keyboard Navigation File

---

.changeset/four-starfishes-glow.md
packages/webapp/src/webview/ui/components/GuidedAnswerNavPath/GuidedAnswerNavPath.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Middle/Middle.tsx
packages/webapp/src/webview/ui/components/utils.ts

#134 
The keyboard focus wasn't reset when a change occurred to the API. This issue has been fixed with this PR

Keyboard Nav focus fixed

---

.changeset/long-birds-tell.md
packages/core/src/guided-answers-api.ts
packages/core/test/guided-answers-api.test.ts
packages/types/src/types.ts

https://github.com/SAP/guided-answers-extension/issues/236
Fix to show more than 20 results.

fix: show more than 20 results

---

docs/testcases/View Guided Answers Content.md

Testcase for user story #96 - Solved, Not solved

---

.changeset/clean-cows-suffer.md

Version number was not increased since last release.
Create new version using changeset.

chore: bump version

---

.changeset/clever-bananas-visit.md

https://github.com/SAP/guided-answers-extension/issues/245
follow up on PR: https://github.com/SAP/guided-answers-extension/pull/274
Add missing changeset to trigger build of vsix.

chore: missing changeset

---

packages/webapp/src/webview/state/reducers.ts

Sonar issue cognitive complexity: https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&id=SAP_guided-answers-extension&open=AYPYGNtVP45B1br8wBbF
Refactor of reducer to reduce cognitive complexity. With the refactoring of the reducer we go away from the `switch`/`case` based approach towards a more modern approach, perhaps as a preparation to switch to slices from redux toolkit in future.

chore: reduce cognitive complexity

---

.changeset/modern-moose-joke.md
packages/core/src/guided-answers-api.ts
packages/core/test/guided-answers-api.test.ts

https://github.com/SAP/guided-answers-extension/issues/279
Fix for images that are not displayed.

fix: images not displayed

---

docs/enhancement-guide.md

How to identify extension and command ids

Update to enhancement.json

---

.changeset/eighty-mails-mate.md
packages/ide-extension/src/panel/guidedAnswersPanel.ts
packages/ide-extension/test/__snapshots__/extension.test.ts.snap

https://github.com/SAP/guided-answers-extension/issues/304
fix - webview loading in BAS

fix - webview loading in BAS

---

.changeset/cool-maps-fly.md
packages/webapp/src/webview/ui/components/App/App.scss
packages/webapp/src/webview/ui/components/App/App.tsx
packages/webapp/src/webview/ui/components/Header/Filters/Filters.scss
packages/webapp/src/webview/ui/components/Header/Filters/FiltersRibbon.scss
packages/webapp/src/webview/ui/components/UIComponentsLib/Icons/Icons.tsx

#299 
Minor UI bugs have been fixed

Search Page bugs fix

---

.changeset/rotten-bugs-wait.md

https://github.com/SAP/guided-answers-extension/issues/299 https://github.com/SAP/guided-answers-extension/issues/306 
Bump version for release.

chore: changeset to bump version and create release

---

packages/ide-extension/src/extension.ts
packages/ide-extension/src/panel/guidedAnswersPanel.ts

Proposed for PR https://github.com/SAP/guided-answers-extension/pull/359 to fix restarting with options.

proposal for feat/ga/reuse-extension-258

---

docs/testcases/View Guided Answers Content_V3.md

Create View Guided Answers Content_V3.md

---

.changeset/brave-drinks-pretend.md
.changeset/warm-islands-talk.md
packages/webapp/package.json
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackSentDialogBox/FeedbackSentDialogBox.tsx
pnpm-lock.yaml

#390
The new icon has been added to open-ui-components through this PR (https://github.com/SAP/open-ux-tools/pull/889)
This pull request consumes the new version of ui-components to replace the icon to match design specs

Fix: Replace Icon in Feedback Sent Dialog Box 

---

.changeset/lemon-hornets-reflect.md
docs/resources/guided-answers-logo.svg

Fresh icon
This is the first to be replaced, just testing among other things.

Updated the icon

---

.changeset/bright-chicken-check.md
docs/resources/guided-answers-logo.svg

Updated logo to have background white plate

---

.changeset/silly-pumpkins-scream.md
packages/webapp/src/webview/ui/components/App/App.scss
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackDialogBox/FeedbackDialogBox.scss
packages/webapp/src/webview/ui/components/Header/Filters/Filters.scss
packages/webapp/src/webview/ui/components/Header/Filters/Filters.tsx
packages/webapp/test/Header/__snapshots__/Filters.test.tsx.snap
packages/webapp/test/Header/__snapshots__/Header.test.tsx.snap
packages/webapp/test/Header/__snapshots__/SearchField.test.tsx.snap
packages/webapp/test/__snapshots__/App.test.tsx.snap

#394 
Bug in returned list fixed, and keyboard navigation on filters also fixed

BUG- FIX  - EXT - Accessibility on filter, GA returned list

---

.changeset/dry-starfishes-tie.md
packages/webapp/src/webview/ui/components/GuidedAnswerNode/GuidedAnswerNode.tsx

https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=SAP_guided-answers-extension&open=AYQ_HtrW5Ay2OOK1m52s
Fix for Sonarqube reported issue

chore: sonar fix

---

.changeset/cold-pigs-pump.md
.changeset/shaggy-swans-taste.md
packages/core/src/guided-answers-api.ts
packages/ide-extension/src/links/link-info.ts
packages/ide-extension/src/panel/guidedAnswersPanel.ts
packages/ide-extension/test/__mocks__/vscode.js
packages/ide-extension/test/extension.test.ts
packages/ide-extension/test/links/guided-answers-uri-handler.test.ts
packages/ide-extension/test/links/link-info.test.ts
packages/ide-extension/test/panel/guidedAnswersPanel.test.ts
packages/types/src/actions.ts
packages/types/src/types.ts
packages/webapp/src/webview/state/actions.ts
packages/webapp/src/webview/state/reducers.ts
packages/webapp/src/webview/ui/components/Header/SearchField/SearchField.tsx

@unseen1980, 
Here is a proposal to update branch `feat/ga/311-shareable-link`:
- Merge two changesets into one
- performance improvement: load node in `getNodePath()` with concurrent requests
- Handle link detection in search query in `guidedAnswersPanel.ts`, no need of additional actions `PARSE_URL` and `URL_USED_IN_SEARCH`
- unit tests for `ide-extension`

feat: proposal for sharable link

---

docs/resources/guided-answers-logo.svg

Wrong icon, decision about new icon pending.

chore: revert icon

---

.changeset/metal-ways-buy.md
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackSentDialogBox/FeedbackSentDialogBox.tsx

https://github.com/SAP/guided-answers-extension/issues/363
setTimeout needs to be in an effect hook and also to clear it.

fix(ga): fix confirmation dialog delay - 363

---

docs/testcases/View Guided Answers Content_V3.md

Test case for user story  #311

---

docs/testcases/View Guided Answers Content_V3.md

Testcases for US #310

---

docs/testcases/View Guided Answers Content_V3.md
packages/webapp/src/webview/ui/components/GuidedAnswerNode/GuidedAnswerNode.scss
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Right/Right.tsx
packages/webapp/test/GuidedAnswerNode/__snapshots__/Right.test.tsx.snap

#310 
Updated the designs of node enhancements

feat(310): change node enhancement design

---

.changeset/blue-chairs-yawn.md
.github/workflows/pipeline.yml
package.json
pnpm-lock.yaml

* Update `pnpm` to `v8.0.0` as minimum engine and also in the CI/CD workflow
* Update changeset config file to use the correct package name

chore: update pnpm to v8.0.0

---

docs/testcases/View Guided Answers Content_V3.md

Update for user story 426

---

.changeset/modern-plums-remain.md
packages/webapp/src/webview/ui/components/Header/Filters/FiltersRibbon.tsx
packages/webapp/src/webview/ui/components/Header/Header.scss
packages/webapp/src/webview/ui/components/Header/NavigationButtons/NavigationButtons.tsx
packages/webapp/test/Header/__snapshots__/FiltersRibbon.test.tsx.snap
packages/webapp/test/Header/__snapshots__/Header.test.tsx.snap
packages/webapp/test/Header/__snapshots__/NavigationButtons.test.tsx.snap
packages/webapp/test/__snapshots__/App.test.tsx.snap

https://github.com/SAP/guided-answers-extension/issues/444

fix(ga): fix a11y issues in  buttons

---

.changeset/weak-dancers-bake.md
packages/webapp/package.json
packages/webapp/src/webview/ui/components/FeedbackSection/FeedbackSection.scss
packages/webapp/src/webview/ui/components/FeedbackSection/NotSolvedMessage/NotSolvedMessage.tsx
packages/webapp/test/FeedbackSection/__snapshots__/NotSolvedMessage.test.tsx.snap
packages/webapp/test/GuidedAnswerNode/__snapshots__/Middle.test.tsx.snap

https://github.com/SAP/guided-answers-extension/issues/474
Fix a11y in button

fix(ga): fix a11y issue

---

.changeset/stupid-lions-reply.md
packages/webapp/src/webview/ui/components/Header/NavigationButtons/NavigationButtons.tsx

https://github.com/SAP/guided-answers-extension/issues/486
Reset copy to clipboard on callout dismiss

fix(ga): reset copy to clipboard on callout dismiss

---

.changeset/curvy-steaks-ring.md
.eslintrc
packages/core/src/guided-answers-api.ts
packages/ide-extension/src/enhancement/enhancements.ts
packages/ide-extension/src/links/guided-answers-uri-handler.ts
packages/ide-extension/src/panel/guidedAnswersPanel.ts
packages/ide-extension/src/telemetry/action-map.ts
packages/ide-extension/src/telemetry/telemetry.ts
packages/webapp/package.json
packages/webapp/src/webview/ui/components/App/App.tsx
packages/webapp/src/webview/ui/components/Bookmarks/Bookmarks.tsx
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackDialogBox/FeedbackDialogBox.tsx
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackSentDialogBox/FeedbackSentDialogBox.tsx
packages/webapp/src/webview/ui/components/DialogBoxes/MessageDialogBox/MessageDialogBox.tsx
packages/webapp/src/webview/ui/components/FeedbackSection/FeedbackSection.tsx
packages/webapp/src/webview/ui/components/FeedbackSection/NotSolvedMessage/NotSolvedMessage.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNavPath/GuidedAnswerNavPath.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/GuidedAnswerNode.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Middle/Middle.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Right/Right.tsx
packages/webapp/src/webview/ui/components/Header/Filters/Filters.tsx
packages/webapp/src/webview/ui/components/Header/Filters/FiltersRibbon.tsx
packages/webapp/src/webview/ui/components/Header/Header.tsx
packages/webapp/src/webview/ui/components/Header/NavigationButtons/NavigationButtons.tsx
packages/webapp/src/webview/ui/components/Header/SearchField/SearchField.tsx
pnpm-lock.yaml

https://github.com/SAP/guided-answers-extension/issues/499
Code hygiene, fix code smells and lint issues.

chore: fix lint issues and code smells

---

.github/workflows/pipeline.yml
package.json

Improvements for `pnpm`.
- set `engines.pnpm` to version `8` in `package.json`
- enable [`corepack`](https://github.com/nodejs/corepack) for developers that use multiple package managers
- use latest version `pnpm@8.5.1` for pipeline run with GitHub actions

chore: version of pnpm, enable corepack support

---

docs/testcases/View Guided Answers Content_V3.md

Update View Guided Answers Content_V3.md - US 492

---

docs/testcases/View Guided Answers Content_V3.md

Test case for US 490

---

.changeset/spotty-crews-remember.md
packages/webapp/src/webview/ui/components/Header/Header.scss
packages/webapp/src/webview/ui/components/Header/NavigationButtons/NavigationButtons.tsx

#485
* Fixed a bunch of bugs related to focus highlighting

fix(485): fix share popup focus highlighting

---

.changeset/mighty-pianos-roll.md
packages/webapp/src/webview/i18n/i18n.json

https://github.com/SAP/guided-answers-extension/issues/512
This pr has following changes in the copy instruction:
1. Removed the `->` characters
2. Removed the `"` around the links
3. Some minor text adjustments

chore: enhance copy instruction text

---

.changeset/good-yaks-yawn.md
packages/webapp/src/webview/ui/components/App/App.scss
packages/webapp/src/webview/ui/components/App/App.tsx
packages/webapp/src/webview/ui/components/Bookmarks/Bookmarks.scss
packages/webapp/src/webview/ui/components/Bookmarks/Bookmarks.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNavPath/GuidedAnswerNavPath.scss
packages/webapp/src/webview/ui/components/Header/Header.scss
packages/webapp/src/webview/ui/components/Header/SearchField/SearchField.tsx
packages/webapp/src/webview/ui/components/LastVisited/LastVisited.tsx
packages/webapp/src/webview/ui/components/TreeItemBottomSection/TreeItemBottomSection.tsx
packages/webapp/test/Header/SearchField.test.tsx
packages/webapp/test/Header/__snapshots__/Header.test.tsx.snap
packages/webapp/test/Header/__snapshots__/SearchField.test.tsx.snap
packages/webapp/test/HomeGrid/__snapshots__/HomeGrid.test.tsx.snap
packages/webapp/test/LastVisited/__snapshots__/LastVisited.test.tsx.snap
packages/webapp/test/TreeItemBottomSection/TreeItemBottomSection.test.tsx
packages/webapp/test/__snapshots__/App.test.tsx.snap

#232
* Fixed bookmark button position in bookmark list
* Removed disabled filter buttons from home screen

fix: fix bookmark and filter positioning

---

.changeset/empty-snails-jog.md
packages/webapp/src/webview/ui/components/Header/Header.tsx
packages/webapp/src/webview/ui/components/HomeGrid/HomeGrid.tsx
packages/webapp/test/App.test.tsx
packages/webapp/test/Header/Header.test.tsx
packages/webapp/test/Header/__snapshots__/Header.test.tsx.snap
packages/webapp/test/HomeGrid/HomeGrid.test.tsx
packages/webapp/test/HomeGrid/__snapshots__/HomeGrid.test.tsx.snap
packages/webapp/test/__snapshots__/App.test.tsx.snap

#232 
* Removed beta toggle for new features

feat(232): remove beta toggle

---

.changeset/silly-seahorses-kick.md
packages/webapp/src/webview/ui/components/Header/Header.scss
packages/webapp/src/webview/ui/components/Header/Logo/Logo.tsx
packages/webapp/test/Header/__snapshots__/Header.test.tsx.snap
packages/webapp/test/__snapshots__/App.test.tsx.snap

#232
* Make title and logo tabbable to with a keyboard

fix(232): make title keyboard accessible

---

.changeset/smart-mugs-live.md
packages/core/src/guided-answers-api.ts
packages/core/test/guided-answers-api.test.ts
packages/ide-extension/package.json
packages/ide-extension/src/bookmarks/bookmarks.ts
packages/ide-extension/src/enhancement/commandHandler.ts
packages/ide-extension/src/extension.ts
packages/ide-extension/src/last-visited/lastVisited.ts
packages/ide-extension/src/links/guided-answers-uri-handler.ts
packages/ide-extension/src/logger/logger.ts
packages/ide-extension/src/panel/guidedAnswersPanel.ts
packages/ide-extension/src/telemetry/telemetry.ts
packages/ide-extension/test/__mocks__/vscode.js
packages/ide-extension/test/bookmarks/bookmarks.test.ts
packages/ide-extension/test/enhancement/commandHandler.test.ts
packages/ide-extension/test/extension.test.ts
packages/ide-extension/test/last-visited/lastVisited.test.ts
packages/ide-extension/test/links/guided-answers-uri-handler.test.ts
packages/ide-extension/test/logger/logger.test.ts
packages/ide-extension/test/panel/guidedAnswersPanel.test.ts
packages/ide-extension/test/telemetry/telemetry.test.ts
packages/types/src/types.ts
pnpm-lock.yaml

https://github.com/SAP/guided-answers-extension/issues/569
Use new [Log output channel](https://code.visualstudio.com/updates/v1_73#_log-output-channel). Although the release note for VSCode `1.73` mentiones `LogOutputChannel`, it available from 1.74.x only. Had to update min VSCode version to `1.74.1`.

chore: new output log

---

.changeset/moody-worms-pump.md
packages/ide-extension/src/panel/guidedAnswersPanel.ts
packages/ide-extension/src/types/index.ts
packages/ide-extension/src/types/telemetry.ts
packages/ide-extension/test/telemetry/telemetry.test.ts

#574
Extends startup options / telemetry interface

feat(ga): extends startup options / telemetry interface

---

.changeset/strange-baboons-drive.md
packages/webapp/.eslintrc
packages/webapp/src/webview/ui/components/App/App.tsx
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackDialogBox/FeedbackDialogBox.tsx
packages/webapp/src/webview/ui/components/DialogBoxes/FeedbackSentDialogBox/FeedbackSentDialogBox.tsx
packages/webapp/src/webview/ui/components/DialogBoxes/MessageDialogBox/MessageDialogBox.tsx
packages/webapp/src/webview/ui/components/ErrorScreen/ErrorScreen.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Middle/Middle.tsx
packages/webapp/src/webview/ui/components/GuidedAnswerNode/Right/Right.tsx
packages/webapp/src/webview/ui/components/Header/Filters/Filters.tsx
packages/webapp/src/webview/ui/components/Header/NavigationButtons/NavigationButtons.tsx
packages/webapp/src/webview/ui/components/HomeGrid/Bookmarks/Bookmarks.tsx
packages/webapp/src/webview/ui/components/HomeGrid/LastVisited/LastVisited.tsx
packages/webapp/src/webview/ui/components/HomeGrid/QuickFilters/QuickFilters.tsx
packages/webapp/src/webview/ui/components/TreeItemBottomSection/TreeItemBottomSection.tsx
packages/webapp/test/GuidedAnswerNode/__snapshots__/Middle.test.tsx.snap
packages/webapp/test/HomeGrid/__snapshots__/HomeGrid.test.tsx.snap
packages/webapp/test/HomeGrid/__snapshots__/LastVisited.test.tsx.snap
packages/webapp/test/HomeGrid/__snapshots__/QuickFilters.test.tsx.snap

Sonar cloud found code smells https://sonarcloud.io/summary/new_code?id=SAP_guided-answers-extension.
Fix for code smell and enable of lint rules:
- `react/prefer-read-only-props`
- `react/hook-use-state`

chore: code smells

---

package.json

chore(deps): update pnpm to v8.14.0

chore(deps): update pnpm to v8.14.0

---

docs/testcases/View Guided Answers Content_V3.md

Home page Phase 1 - Update View Guided Answers Content_V3.md

---

.github/workflows/pipeline.yml

No Issue
Consume v2.1 of sonar cloud to fix failing PR builds. 
This is also in alignment with open-ux-tools https://github.com/SAP/open-ux-tools

chore: consume v2.1 of sonar cloud to fix failing PR builds

---

.changeset/proud-steaks-clap.md
.github/workflows/pipeline.yml
packages/webapp/package.json
pnpm-lock.yaml

#595 
Also solves security issue https://github.com/SAP/guided-answers-extension/security/dependabot/11
Consume the latest version of @sap-ux/ui-components to consume security fix for sanitize-html package

chore: update @sap-ux/ui-components to 1.15.2 - solves security issue (#595)

---

.changeset/lemon-mangos-deny.md
.github/workflows/pipeline.yml
package.json
pnpm-lock.yaml

Dependabot alert - https://github.com/SAP/guided-answers-extension/security/dependabot/12
Update follow-redirects due to security issue reported by Dependabot.

chore: update follow-redirects to 1.15.6 due to security

---

.changeset/twenty-trees-applaud.md
pnpm-lock.yaml

#595 
Update transitive dependencies by running `pnpm update`

chore: update transitive dependencies (#595)

---

.changeset/dirty-bikes-breathe.md
package.json
packages/core/package.json
pnpm-lock.yaml

Dependabot alert - https://github.com/SAP/guided-answers-extension/security/dependabot/12
- Update axios due to solve security issue reported by Dependabot for follow-redirects (Issue was not fully solved with earlier PR as override was using <1.15.4)
- Update bas-sdk
- Remove override for follow-redirect

chore: update bas-sdk and axios, remove override

---

packages/ide-extension/esbuild.js
packages/webapp/esbuild.js
pnpm-lock.yaml

Run `pnpm watch` in `webapp` and `ide-extension` folders to load source maps

fix - load webapp source maps

---

.changeset/fast-taxis-shake.md
package.json
packages/core/package.json
pnpm-lock.yaml

https://github.com/SAP/guided-answers-extension/security/dependabot/16 and https://github.com/SAP/guided-answers-extension/security/dependabot/15
Update `axios` to `1.7.4` to solve security issues.
An update of `pretty-quick` was also required to solve an issue with unmet peer dependency. As a result pre commit husky check was also failing.

chore: update axios for security and pretty-quick

---

.changeset/ninety-adults-count.md
packages/core/package.json
pnpm-lock.yaml

https://github.com/SAP/guided-answers-extension/security/dependabot/16
Update bas-sdk to 3.8.9 to fix the security issue reported by dependabot

security: update bas-sdk to 3.8.9

---

.github/workflows/pipeline.yml

No issue
Update actions to fix the broken pipeline.

chore: update sonarcloud actions to v4 fix broken pipeline

---

.changeset/swift-peaches-pump.md
.github/workflows/pipeline.yml
package.json
pnpm-lock.yaml

#595 
GHSA-3xgq-45jj-v275
CVE-2024-21538

security: use cross-spawn version 7.0.5 and above

---

.changeset/quick-terms-suffer.md
.github/workflows/pipeline.yml
pnpm-lock.yaml

#595 
Update transitive dependencies by running `pnpm update`

chore: update transitive dependencies
